### ISSUE TITLE
Logo in title bar in mobile view

### ISSUE THREAD

**Issue by ayushjainrksh** [CSEC-NITH/csec-website-new#19]
When website in viewed in mobile view and refreshed, CSEC logo disappears from the title bar.

**Comment by no-one-21** [comment]
there is no such kind of issue happening in neither of my chrome  nor in my  firefox browser. can please be a more specific about issue details ,or may be i am understanding it wrong.

**Comment by ayushjainrksh** [comment]
I just restarted my browser, seems perfect now.
